version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd_network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    depends_on:
      - sonarqube

  # Keeping your existing SonarQube services
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_QUIET=true
    ports:
      - "9000:9000"
    networks:
      - cicd_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: sonar-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - cicd_network
    ports:
      - "5433:5432"

networks:
  cicd_network:
    driver: bridge

volumes:
  jenkins_home: